""""
Prompt1（Preliminary Construction of the Ontology Model）:

You are an expert with a deep understanding of hospital medical records. Based on this national standard clinical pathway, please construct a multi-level classification ontology model for the treatment process. The ontology model should have a clear structure, where lower-level concepts are subsets of higher-level concepts. The ontology construction should start with the different stages of hospitalization, further subdividing each stage into all necessary activities. The model should comprehensively reflect the various category concepts included in the hospitalization process.

I will provide you with a clinical pathway document. This clinical pathway divides the hospitalization process into six stages in chronological order. Each stage specifies the key medical tasks, important medical orders, main nursing tasks, and records of disease variation that need to be carried out during the current treatment phase, all of which form the key diagnostic and therapeutic activities of the hospitalization process. Although the clinical pathway form cannot detail every diagnostic and therapeutic activity that needs to be carried out during the hospitalization, it provides the basic framework and guidance for treatment activities.

Therefore, you need to understand the structural logic of the clinical pathway and the relationships between the diagnostic and therapeutic tasks of different stages. Following the division rules of the clinical pathway stages, treat each stage as a sub-ontology in the ontology model. Expand each sub-ontology according to the diagnostic and therapeutic tasks of each stage to create an ontology model that conforms to the logical structure of the clinical pathway. Please output the ontology model using the Protégé syntax.

The content of the National Standard Clinical Pathway is as follows:
The clinical pathway divides the hospitalization process into six stages, namely the admission day, preoperative day, surgery day, postoperative day 1, postoperative recovery day, and discharge day.
Admission Day is the first day of hospitalization. The main diagnostic and treatment activities include taking the patient’s medical history and conducting a physical examination, completing the medical record, issuing laboratory and examination requisitions, conducting the attending physician's rounds, and making a preliminary diagnosis. Key medical orders are divided into long-term and short-term orders. Long-term orders include secondary nursing care and regular diet in the thoracic surgery department, while short-term orders include routine blood tests, urinalysis, stool tests, coagulation function, blood type, liver function, kidney function, electrolytes, infectious disease screening, pulmonary function tests, arterial blood gas analysis, electrocardiogram (ECG), sputum cytology, fiberoptic bronchoscopy, and imaging tests such as chest X-ray, chest CT, abdominal ultrasound or CT, whole-body bone scan, and cranial MRI or CT. Main nursing activities include introducing the ward environment, facilities, and equipment, conducting the admission nursing assessment, and assisting in smoking cessation. The record of disease variation should include whether the patient’s condition has changed and the reasons for such changes.
Preoperative Day spans from the second day to the sixth day of hospitalization. Major diagnostic and treatment activities include rounds by the senior physician, preoperative preparation, clinical staging, and preoperative evaluation, preoperative discussions, determining the surgical plan, consultations with relevant departments as needed, the inpatient physician’s completion of the progress notes and preoperative summary, rounds by the senior physician, signing the surgical informed consent, personal expense agreement, blood transfusion consent, and power of attorney consent. Key medical orders include nebulized inhalation, fasting and water restrictions for 6 hours before surgery, enema before surgery, shaving, blood preparation, preoperative sedation (if necessary), intraoperative antimicrobial prophylaxis, and other special orders such as mediastinoscopy, 24-hour Holter monitoring, echocardiogram, percutaneous lung biopsy, etc. Major nursing activities include preoperative education, skin preparation, and reminding patients about preoperative fasting and respiratory function exercises. The record of disease variation should include whether the patient’s condition has changed and the reasons for such changes.
Surgery Day spans from the fourth day to the seventh day of hospitalization. Major diagnostic and treatment activities include preoperative urinary catheter placement, surgery, surgical record by the surgeon, postoperative progress notes by the inpatient physician, rounds by the senior physician, monitoring vital signs, and communicating the patient’s condition and postoperative care instructions to the patient and family. Key medical orders include thoracic surgery postoperative nursing protocols, special or primary nursing care, liquid diet 6 hours after waking, oxygen therapy, monitoring temperature, ECG, blood pressure, respiratory rate, pulse, oxygen saturation, recording chest tube drainage, continuous catheterization, recording 24-hour input/output, nebulized inhalation, prophylactic antibiotic therapy, and pain relief. Major nursing activities include observing changes in the patient’s condition, postoperative psychological and life care, and ensuring airway patency. The record of disease variation should include whether the patient’s condition has changed and the reasons for such changes.
Postoperative Day 1 spans from the fifth to the eighth day of hospitalization. Major diagnostic and treatment activities include rounds by the senior physician, progress notes by the inpatient physician, observing chest tube drainage, monitoring vital signs and lung auscultation, encouraging and assisting the patient in expectorating, and performing bronchoscopy for sputum suction if necessary. Key medical orders include thoracic surgery level 1 nursing, regular diet, routine blood tests, liver and kidney function tests, electrolytes, and chest X-ray. Major nursing activities include observing the patient’s condition, psychological and life care, and assisting the patient in coughing up sputum. The record of disease variation should include whether the patient’s condition has changed and the reasons for such changes.
Postoperative Recovery Day spans from the second day to the seventh day after surgery. Major diagnostic and treatment activities include rounds by the senior physician, progress notes by the inpatient physician, reviewing routine blood tests, blood biochemistry, and chest X-ray as needed, removal of the chest tube and dressing change when appropriate based on the chest tube drainage and lung re-expansion, and discontinuing or adjusting antibiotic therapy if necessary. Key medical orders include thoracic surgery level 2 nursing, cessation of chest closed drainage measurements, cessation of urine output measurement, cessation of oxygen therapy, cessation of ECG monitoring, cessation of nebulization, cessation of antibiotics, removal of chest closed drainage tube, removal of urinary catheter, dressing change, rechecking chest X-ray or chest CT, routine blood tests, liver and kidney function, electrolytes. Major nursing activities include observing the patient’s condition, psychological and life care, and assisting the patient in coughing up sputum. The record of disease variation should include whether the patient’s condition has changed and the reasons for such changes.
Discharge Day spans from the eighth to the fourteenth day after surgery. Major diagnostic and treatment activities include suturing of the incision, rounds by the senior physician to confirm discharge, completion of the discharge summary by the inpatient physician, providing discharge instructions to the patient and family, and determining the postoperative treatment plan based on the postoperative pathology report. Key medical orders include incision suturing, dressing change, discharge notification, discharge medications, and follow-up appointments. Major nursing activities include observing changes in the patient’s condition, psychological and life care, and postoperative rehabilitation guidance. The record of disease variation should include whether the patient’s condition has changed and the reasons for such changes.
"""

"""
Prompt2（Further Optimization of the Ontology Model, Using Admission Day as an Example）:

The above ontology model is based on the national standard clinical pathway; however, in actual treatment processes, hospitals may adjust certain treatment activities according to their specific circumstances. Please revise the Admission Day portion of the ontology model based on the specific event principles of the hospital's treatment process I provided, ensuring that the ontology model aligns more closely with actual practice.

(1) The hospital's history-taking process needs to understand the patient's disease course, medical history characteristics, and the patient's concerns.
(2) The patient's admission physical examination needs to include both lung and physical examinations. The patient’s medical records are written during the doctor's rounds, which also include evaluations and auxiliary examination assessments.
(3) In addition, the diagnostic and therapeutic tasks include formulating a treatment plan. Laboratory tests and imaging examinations are included, and it is also necessary to understand the patient's surgical contraindications and formulate VTE (Venous Thromboembolism) risk prevention measures.
"""